export const ROUTES = {
    HOME: '/',
    ADMIN: '/admin',
    USER: '/user',
    CALENDAR: '/calendar',
    PROFILE: '/profile',
    FORM_ELEMENTS: '/form-elements',
    FORM_LAYOUT: '/form-layout',
    BASIC_TABLES: '/basic-tables',
    DATA_TABLES: '/data-tables',
    BLANK: '/blank',
    INTERNALSERVERERROR: '/error-500',
    SERVICEUNAVAILABLE: '/error-503',
    MAINTENANCE: '/maintenance',
    SUCCESS: '/success',
    LINE_CHART: '/line-chart',
    BAR_CHART: '/bar-chart',
    PIE_CHART: '/pie-chart',
    SALES: '/sales',
    LOGIN: '/login',
    REGISTER: '/register',
    CONFIRM_EMAIL: '/confirm-email',
    RESEND_VERIFICATION: '/resend-verification',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    FORBIDDEN: '/forbidden',
    NOT_FOUND: '*',
};
